name: learning permissions
on: push
jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "holaa" >> README.md
          git config --global user.email "gacbot@noreply.com"
          git config --global user.name "GAC Bot"
          git add .
          git commit -m "add README.md"
          git push
